/**
 * The published size table in `docs/consumption.md`, owned by the gate that measures it.
 *
 * The table used to be typed by hand and drifted the moment a component grew. Now
 * `check:tree-shaking --write` renders it between two marker comments, and a plain
 * `check:tree-shaking` fails when the committed block no longer matches what it
 * measures.
 *
 * "Matches" is structural equality plus a numeric tolerance, not byte equality. The
 * bundles themselves are deterministic — same lockfile, same Rollup and esbuild
 * output on every platform — but the gzip step is not: `node:zlib` is whichever
 * deflate build the runtime links, and the macOS and Linux builds of Bun can choose
 * different matches at the same level. That moves a size by a few bytes to a few
 * tenths of a percent; it never moves it by a whole percent. So a committed figure
 * passes when it is within {@link TOLERANCE} of the measured one — loose enough that
 * a table written on a laptop passes on the Linux runner, tight enough that the
 * 86.2 → 88.9 kB kind of drift (3%) fails.
 */

export const START_MARKER =
  '<!-- tree-shaking:start — generated by `bun run check:tree-shaking --write`; do not edit by hand -->'
export const END_MARKER = '<!-- tree-shaking:end -->'

/** A committed figure passes when within the larger of these of the measured one. */
export const TOLERANCE = {
  /** Absolute floor, in kB, so the smallest bundles are not held to a few bytes. */
  kB: 0.3,
  /** Relative allowance for every kB figure. */
  relative: 0.015,
  /** Absolute allowance for a percentage figure, in percentage points. */
  percentPoints: 0.3,
} as const

export type SizeRow = {
  /** The public entry, e.g. `@adea-ai/ui/components/ui/chart`. */
  entry: string
  name: string
  /** What the import brings with it, for the reader. */
  brings: string
  gzip: number
}

export type SizeReport = {
  rows: readonly SizeRow[]
  /** The root plus the optional chart and carousel entries, gzipped. */
  whole: number
  /** `Button` alone, gzipped — the one-component floor the ratio is taken from. */
  one: number
  lineChart: number
  allCharts: number
  budgets: {
    oneComponentBytes: number
    heaviestComponentBytes: number
    ratioOfWholeLibrary: number
  }
}

/** Bytes as kB with one decimal, the unit the docs and the report both use. */
export function kb(bytes: number): string {
  return `${(bytes / 1024).toFixed(1)} kB`
}

function percent(ratio: number): string {
  return `${(ratio * 100).toFixed(1)}%`
}

/** A Markdown table padded the way the formatter pads it, so `fmt` leaves it alone. */
function table(header: readonly string[], body: readonly (readonly string[])[]): string[] {
  const widths = header.map((cell, column) =>
    Math.max(3, cell.length, ...body.map((row) => row[column]!.length))
  )
  const line = (cells: readonly string[]) =>
    `| ${cells.map((cell, column) => cell.padEnd(widths[column]!)).join(' | ')} |`
  return [line(header), line(widths.map((width) => '-'.repeat(width))), ...body.map(line)]
}

/** The block between the markers, markers included. */
export function renderSizeBlock(report: SizeReport): string {
  const body = report.rows.map((row) => [
    `\`${row.entry}\` → \`${row.name}\``,
    kb(row.gzip),
    row.brings,
  ])
  body.push([
    '_root plus chart and carousel entries_',
    `_${kb(report.whole)}_`,
    `— and \`Button\` is ${percent(report.one / report.whole)} of it`,
  ])
  const { budgets } = report
  return [
    START_MARKER,
    '',
    ...table(['Public import', 'Gzipped', 'What it brings'], body),
    '',
    'The chart splits from itself, which is why chart.js was chosen: `LineChart` is',
    `${kb(report.allCharts - report.lineChart)} smaller than importing all seven chart types together ` +
      `(${kb(report.lineChart)} against ${kb(report.allCharts)}), because the`,
    'controllers are imported per component while the shared scales and plugins are',
    'registered once. The gate fails if that stops being true.',
    '',
    `Three budgets are enforced in CI: importing \`Button\` must stay under ${kb(budgets.oneComponentBytes)}`,
    `and under ${percent(budgets.ratioOfWholeLibrary)} of the whole library, and no sampled component may exceed`,
    `${kb(budgets.heaviestComponentBytes)}.`,
    '',
    END_MARKER,
  ].join('\n')
}

/** The committed block, markers included, or `undefined` when the markers are missing. */
export function extractSizeBlock(doc: string): string | undefined {
  const start = doc.indexOf(START_MARKER)
  const end = doc.indexOf(END_MARKER)
  if (start === -1 || end === -1 || end < start) return undefined
  return doc.slice(start, end + END_MARKER.length)
}

/** `doc` with its block replaced by `block`. Throws when the markers are missing. */
export function replaceSizeBlock(doc: string, block: string): string {
  const current = extractSizeBlock(doc)
  if (current === undefined) {
    throw new Error(`size table markers not found; add ${START_MARKER} … ${END_MARKER}`)
  }
  return doc.replace(current, () => block)
}

const FIGURE = /(\d+(?:\.\d+)?)( kB|%)/g

type Figure = { value: number; unit: ' kB' | '%' }

/**
 * Split a block into its words and its figures. Whitespace runs and the
 * separator-row dashes are collapsed, so a column that widens by one character
 * when a figure gains a digit does not count as a structural change.
 */
function parse(block: string): { shape: string; figures: Figure[] } {
  const figures: Figure[] = []
  const shape = block
    .replace(FIGURE, (_match, value: string, unit: Figure['unit']) => {
      figures.push({ value: Number(value), unit })
      return `#${unit}`
    })
    .replace(/-{3,}/g, '---')
    .replace(/\s+/g, ' ')
    .trim()
  return { shape, figures }
}

function within(committed: Figure, measured: Figure): boolean {
  const delta = Math.abs(committed.value - measured.value)
  if (measured.unit === '%') return delta <= TOLERANCE.percentPoints + 1e-9
  return delta <= Math.max(TOLERANCE.kB, measured.value * TOLERANCE.relative) + 1e-9
}

/**
 * Why the committed block no longer describes what was measured — empty when it
 * still does. Each finding names the figure and both values.
 */
export function compareSizeBlocks(committed: string, measured: string): string[] {
  const left = parse(committed)
  const right = parse(measured)
  if (left.shape !== right.shape || left.figures.length !== right.figures.length) {
    return ['the committed size table differs in wording or rows from what the gate renders']
  }
  const findings: string[] = []
  right.figures.forEach((figure, index) => {
    const was = left.figures[index]!
    if (!within(was, figure)) {
      findings.push(
        `figure ${index + 1}: committed ${was.value}${was.unit}, measured ${figure.value}${figure.unit}`
      )
    }
  })
  return findings
}
